spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payment_gateway
    username: gateway_user
    password: gateway_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}

server:
  port: 8000

app:
  role: ${APP_ROLE:API}